//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W11_01_AutoController
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Total_Product_Sale
    {
        public Nullable<int> EmployeeID { get; set; }
        public int ProductID { get; set; }
        public Nullable<double> TotalPrice { get; set; }
    }
}
