// <auto-generated />
namespace W08_02_EF_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class create_column_hour_table_lecture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_column_hour_table_lecture));
        
        string IMigrationMetadata.Id
        {
            get { return "202202240824256_create_column_hour_table_lecture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
