// <auto-generated />
namespace W08_02_EF_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class rename_lecture_name_lecturename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_lecture_name_lecturename));
        
        string IMigrationMetadata.Id
        {
            get { return "202202240847104_rename_lecture_name_lecturename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
